# Generated by Django 4.2.4 on 2023-08-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berealapp', '0003_alter_product_total_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item_name',
            new_name='product_name',
        ),
    ]
